version: 0.2

env:

  shell: bash

  variables:
     REPOSITORY_URI: $REPOSITORY_URI
     SERVICE: $SERVICE
     ENV: $ENV
  
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - docker build -t $REPOSITORY_URI/$SERVICE:$ENV-$CODEBUILD_BUILD_NUMBER .
      - docker tag $REPOSITORY_URI/$SERVICE:$ENV-$CODEBUILD_BUILD_NUMBER $REPOSITORY_URI/$SERVICE:$ENV-latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI/$SERVICE:$ENV-$CODEBUILD_BUILD_NUMBER
      - docker push $REPOSITORY_URI/$SERVICE:$ENV-latest
artifacts:
  files:
    - buildspec.yml
#cache:
  #paths:
    # - paths